### ISSUE TITLE
unexpected output from innobackupex

### ISSUE THREAD

**Issue by cwmedia** [robbertkl/pxcbackup#1]
Hello.

I have problem creating backup:

pxcbackup create -d /home/backup -f -l --verbose
Setting wsrep_desync=ON
Waiting for 60 seconds: done (60.0s)
Creating backup 1505318290_full.xbstream: fail
/usr/local/bin/pxcbackup: unexpected output from innobackupex

innobackupex version 2.4.8 Linux (x86_64) (revision id: 97330f7)
pxcbackup 0.2.1

**Comment by robbertkl** [comment]
Is it possible for you to edit and debug a bit? If you can edit `backupper.rb` and insert a `puts command` right before the line `result = Command.run(command)`, it should show you the full innobackupex command when running.

Then, you could manually run this command to see what error it's throwing.

**Comment by cwmedia** [comment]
Output was: 
xtrabackup: Error: unknown argument: '/tmp/pxcbackup-20170914-11664-1lpn9lk'

So it looks like innobackupex expects backup dir path to be last argument, but in innobackupex function there are some arguments added by arguments +=. I replaced all += with unshift() in this function and it seems to work ok now.

**Comment by robbertkl** [comment]
Thanks for finding that out! I guess that's a more recent change, since it was working fine before.

If you could create a PR with your changes, I'd be happy to merge it and create a new release.

**Comment by cwmedia** [comment]
There is one more thing that should be added if we are using xtrabackup version 2.4.8 (it comes with cluster version 5.7), as described here:
https://www.percona.com/blog/2017/08/08/avoiding-the-an-optimized-without-redo-logging-ddloperation-has-been-performed-error-with-percona-xtrabackup/

There is new option: --lock-ddl

It will probably break compatibility with version 5.6, so some version chcecking or new options in config should be added. I'm not rubby programmer, so I can't help with that, I just hardcoded it to my local copy.

**Comment by robbertkl** [comment]
OK, that can be handled in a different issue. Thanks!
